apiVersion: v1
kind: ConfigMap
metadata:
  name: chronoflow-config
  namespace: chronoflow
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/chronoflow"
  SPRING_DATASOURCE_USERNAME: "chronoflow"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector:4318/v1/traces"
