apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chronoflow
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - configmap.yaml
  - secret.yaml
  - job-service.yaml
  - auth-service.yaml
  - scheduler-service.yaml
  - executor-service.yaml
  - api-gateway.yaml
