apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronoflow.fullname" . }}-config
  labels:
    {{- include "chronoflow.labels" . | nindent 4 }}
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redisHost | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.config.redisPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.datasourceUsername | quote }}
  MANAGEMENT_OTLP_TRACING_ENDPOINT: {{ .Values.global.tracingEndpoint | quote }}
